// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTgVJMzsJTWMJ5AI4Sl7e9Uc2r6VIuG3Q',
    appId: '1:896696900132:web:2461791c36ac3431fbd6b1',
    messagingSenderId: '896696900132',
    projectId: 'ambrosia-ayurved',
    authDomain: 'ambrosia-ayurved.firebaseapp.com',
    storageBucket: 'ambrosia-ayurved.firebasestorage.app',
    measurementId: 'G-55JED39KDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLypEENTWXsHXPmkpwx4jb1OxJPnTRPNc',
    appId: '1:896696900132:android:ecffa0bde986342afbd6b1',
    messagingSenderId: '896696900132',
    projectId: 'ambrosia-ayurved',
    storageBucket: 'ambrosia-ayurved.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfLIRPNo8yXApzBtTaCcLcM3-7phyP8b8',
    appId: '1:896696900132:ios:32272c72efb8ae6afbd6b1',
    messagingSenderId: '896696900132',
    projectId: 'ambrosia-ayurved',
    storageBucket: 'ambrosia-ayurved.firebasestorage.app',
    iosBundleId: 'com.app.ambrosiaayurved',
  );
}
